IF OBJECT_ID (CONCAT('dbo.', QUOTENAME(@TableName)), N'U') IS NOT NULL
--IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = @TableName)
BEGIN 
    SELECT 1 
END 
ELSE 
BEGIN 
    SELECT 0 
END 